update vm test

diff --git a/.github/workflows/vm_test.yml b/.github/workflows/vm_test.yml
--- a/.github/workflows/vm_test.yml
+++ b/.github/workflows/vm_test.yml
@@ -21,15 +21,19 @@ jobs:
           SSH_PASSWORD: ${{ secrets.PASSWORD }}
           DEPLOY_USER: ${{ secrets.USERNAME }}
         run: |
-          if sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 $DEPLOY_USER@$DEPLOY_SERVER "exit"; then
-            ls -la
-            whoami
-            docker run -p 7777:2222 cowrie/cowrie:latest -d
-            echo "SSH on port 66 succeeded as expected"
-          else
-            echo "SSH on port 66 failed unexpectedly"
-            exit 1
-          fi
+            if sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 "$DEPLOY_USER@$DEPLOY_SERVER" "exit"; then
+                echo "SSH on port 66 succeeded as expected"
+            
+                # Run commands inside the VM
+                sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 "$DEPLOY_USER@$DEPLOY_SERVER" << 'EOF'
+                    ls -la
+                    whoami
+                    docker run -p 7777:2222 -d cowrie/cowrie:latest
+                EOF
+            else
+                echo "SSH on port 66 failed unexpectedly"
+                exit 1
+            fi
 
       - name: Honeypot VM
         env:
