update vm test

diff --git a/.github/workflows/vm_test.yml b/.github/workflows/vm_test.yml
--- a/.github/workflows/vm_test.yml
+++ b/.github/workflows/vm_test.yml
@@ -15,25 +15,38 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y sshpass git
 
+      - name: Test SSH on port 22
+        env:
+          DEPLOY_SERVER: ${{ secrets.IP }}
+          SSH_PASSWORD: ${{ secrets.PASSWORD }}
+          DEPLOY_USER: ${{ secrets.USERNAME }}
+        run: |
+          if sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 22 $DEPLOY_USER@$DEPLOY_SERVER "exit"; then
+            echo "SSH on port 22 succeeded unexpectedly"
+            exit 1
+          else
+            echo "SSH on port 22 failed as expected"
+          fi
+
       - name: Test SSH on port 66
         env:
           DEPLOY_SERVER: ${{ secrets.IP }}
           SSH_PASSWORD: ${{ secrets.PASSWORD }}
           DEPLOY_USER: ${{ secrets.USERNAME }}
         run: |
-            if sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 "$DEPLOY_USER@$DEPLOY_SERVER" "exit"; then
-                echo "SSH on port 66 succeeded as expected"
+          if sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 $DEPLOY_USER@$DEPLOY_SERVER "exit"; then
+            echo "SSH on port 66 succeeded as expected"
             
-                # Run commands inside the VM
-                sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 "$DEPLOY_USER@$DEPLOY_SERVER" << 'EOF'
-                    ls -la
-                    whoami
-                    docker run -p 7777:2222 -d cowrie/cowrie:latest
-                EOF
-            else
-                echo "SSH on port 66 failed unexpectedly"
-                exit 1
-            fi
+            # Run commands inside the VM
+            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 66 $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
+              ls -la
+              whoami
+              docker run -p 7777:2222 -d cowrie/cowrie:latest
+            EOF
+          else
+            echo "SSH on port 66 failed unexpectedly"
+            exit 1
+          fi
 
       - name: Honeypot VM
         env:
